---

dependencies: []

galaxy_info:
  author: Markus Binsteiner
  description: 'molecule/default described in 1 sentence...'
  company: 
  license: GPLv3
  min_ansible_version: '1.7.1'
  platforms:
    - name: Ubuntu
      versions:
        - precise
        - trusty
    - name: Debian
      versions:
        - wheezy
        - jessie
  categories: []

ansigenome_info:
  galaxy_id: ''

  travis: True

  synopsis: |
    molecule/default described in a few paragraphs....

  usage: |
    Describe how to use molecule/default...

  #custom: |
  #  Any custom output you want after the usage section...
